#!/bin/bash

if [ "${MLIBDIR}" ];then
  sed -i -e "s/\${exec_prefix}\/lib\/lib/-l/g"  -e "s/\.so//g" ${3}/usr/${B_LIBDIRS}/${MLIBDIR}/pkgconfig/opencv.pc
 else
  sed -i -e "s/\${exec_prefix}\/lib\/lib/-l/g"  -e "s/\.so//g" ${3}/usr/${B_LIBDIRS}/pkgconfig/opencv.pc
fi
